title: GPC 한국어판
description: GPC 프로젝트를 사용하는 방법을 다루고 있습니다
remote_theme: just-the-docs/just-the-docs@v0.10.0

url: 'https://leoppark94.github.io'
baseurl: '/Gitlab_Project_Configurator_Korean'

aux_links:
  "Original Repository":
    - "//github.com/leoppark94/Gitlab_Project_Configurator_Korean"

aux_links_new_tab: true

search_enabled: true

exclude:
  - README.md
